<a href="https://colab.research.google.com/github/moulya16/ML-LAB/blob/main/Prog5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree, metrics,model_selection,preprocessing 
from sklearn.metrics import confusion_matrix

 #load the iris data

df = pd.read_csv('iris.csv')

df.head(5)

df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

#select features

y = df['species_label']
x = df[['sepal.length','sepal.width','petal.length','petal.width']]

#split data randomly into 70% training and 30% test

x_train,x_test,y_train,y_test = model_selection.train_test_split(x,y,test_size = 0.3,random_state=0)



dtree = tree.DecisionTreeClassifier(criterion = 'gini',max_depth = 3)
dtree.fit(x_train,y_train)

#testing the model

y_pred = dtree.predict(x_test)

 

 
 



 

  

In [11]:
accuracy = metrics.accuracy_score(y_test,y_pred)
print('Accuracy:{:.2f}'.format(accuracy))

Accuracy:0.98


In [12]:
print(confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
